version: "3.8"

services:
  app:
    build: ./
    command: ./app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
  db:
    restart: always
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432